### ISSUE TITLE
Deaths in Pennsylvania seem to have been updated with tested (?) counts.

### ISSUE THREAD

**Issue by roboton** [covidatlas/coronadatascraper#1014]
![image](https://user-images.githubusercontent.com/6075595/82362739-a4275380-99c1-11ea-9848-761a1cdbfe2d.png)

This seems to have happened for several (maybe all?) counties in Pennsylvania. Also pasted below in case image doesn't work:

2020-05-15:Object
cases:50
deaths:1
tested:3036
growthFactor:1
2020-05-16:Object
cases:50
deaths:1
tested:3040
growthFactor:1
2020-05-17:Object
cases:50
deaths:1
tested:3060
growthFactor:1
2020-05-18:Object
cases:50
deaths:3015
tested:3065
growthFactor:1
state:"Pennsylvania"
country:"United States"
aggregate:"county"
sources:Array[1]
url:"https://www.health.pa.gov/topics/disease/coronavirus/Pages/Cases.aspx"
county:"Montour County"

**Comment by roboton** [comment]
Another example:

![image](https://user-images.githubusercontent.com/6075595/82363616-e9985080-99c2-11ea-8c6d-ea0254324bd7.png)

**Comment by roboton** [comment]
The deaths data is on a different page:
https://www.health.pa.gov/topics/disease/coronavirus/Pages/Death-Data.aspx

Than the cases data:
https://www.health.pa.gov/topics/disease/coronavirus/Pages/Cases.aspx

**Comment by edwlook** [comment]
+1 seeing this issue too

**Comment by jzohrab** [comment]
Pep, the PA scraper code isn't nearly careful enough:

https://github.com/covidatlas/coronadatascraper/blob/master/src/shared/scrapers/US/PA/index.js#L279

It's assuming that the page structure doesn't change, which is no good.  Thanks for the issue, @roboton and @edwlook .

**Comment by jzohrab** [comment]
It appears that this just started happening today:

| date | deaths |
| --- | --- |
| '2020-05-17' | 4403 |
| '-18' | 4418 |
| '-19' | 277553 |

So that's nice, less lag in getting the fix in.  Should be quick, I'll add that now.

**Comment by jzohrab** [comment]
Thanks again @roboton , I've merged a fix in for this.  Please LMK if this resolves the issue.  Cheers! jz

**Comment by jzohrab** [comment]
(whoops closed by accident)

**Comment by roboton** [comment]
Hm should it be updated on the main site? I still see really large death
counts from Pennsylvania at this url:
https://coronadatascraper.com/#timeseries-byLocation.json

[image: image.png]
https://coronadatascraper.com/#timeseries-byLocation.json

Just wanted to say how awesome CDS is and grateful for what you all are
doing.

**Comment by jzohrab** [comment]
Right, I see a correction for the last run for the last date, but not the prior date.  Here's from that URL, for Northampton again:

![image](https://user-images.githubusercontent.com/1637133/82451089-86b6c000-9a7b-11ea-8843-a5d071bd3fdf.png)

I just have to adjust the fix to be back one more day, and then we should be good.  I hope!  Fixing now, it should be resolved tomorrow.

**Comment by jzohrab** [comment]
(undo github auto-close)  Cheers and thanks for following up!

**Comment by roboton** [comment]
Looks good! Thanks for fixing @jzohrab
