### ISSUE TITLE
Incorrect lat/long/tz for various countries

### ISSUE THREAD

**Issue by tautme** [covidatlas/coronadatascraper#478]
This is from data.csv March 28
Should tz = "America?"
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/15580867/77840342-0f844000-714c-11ea-9b87-79bfddda0609.png">

**Comment by lazd** [comment]
Should 100% be `aggregate: 'state'`, but the timezone is hilariously wrong.

**Comment by tautme** [comment]
Lat. Long. for USA also incorrect. 
The aggregate labels for country total cases are not consistent. 
<img width="758" alt="image" src="https://user-images.githubusercontent.com/15580867/77843612-70b80d80-7164-11ea-95cb-428b31aa63c2.png">

**Comment by lazd** [comment]
lat long is definitely wrong, and that's why it's finding the wrong timezone. 

Please use separate issues to discuss separate issues. Don't pile on a report about `aggregate` to an issue about `tz`, please.

**Comment by fordmaxson** [comment]
Also noting poor Lat/Long at 'country' level for France, USA, Spain, and Portugal

![image](https://user-images.githubusercontent.com/38134430/78367367-f5a18d80-758f-11ea-9ff3-6b643661be00.png)

**Comment by hyperknot** [comment]
How is it possible that lat-long is incorrect? Aren't we using turf.centroid on the GeoJSON?

**Comment by hyperknot** [comment]
Ah, I know what is happening, all those have overseas territorries, so the centroid is in the middle of the ocean! They'll be fixed once we move to iso codes and look for the right region.

For France for example it's iso1:FX instead of iso1:FR. For the other ones we have to look up the right codes / areas and check the GeoJSON.

**Comment by lazd** [comment]
@tautme thanks again for the report. We completed the move to ISO codes with the 2020-4-5 data. Can you please verify that these are fixed, and close the issue if so? Thanks!

**Comment by tautme** [comment]
Not fixed.
Looks like "United States" has changed to tz = Africa/Algers & lat,log (28.4, 0.3)
line 585 in April 5 data.csv
`
585:United States,country,,,,United States,332308,9498,,1779357,,325145963,28.4065,0.30750000000000455,https://covidtracking.com/api/states,state,0.45098039215686275,Africa/Algiers,iso1:US,iso1:US,,,,
`

**Comment by tautme** [comment]
I sorted by abs(long) to find these.
Fiji, Russia, Alaska *2 , and New Zealand coordinates off.
data.csv line number listed
![image](https://user-images.githubusercontent.com/15580867/78591776-951d8500-7809-11ea-9383-412011d40e3f.png)

**Comment by hyperknot** [comment]
@tautme can you check if the coordinate in here are OK?
https://github.com/hyperknot/country-levels/blob/master/export/iso1.json

**Comment by tautme** [comment]
@hyperknot I checked the country level iso1 for `RU`, `FJ`, `US` in your `iso1.json`
They are all different from (lat, lon) in data.csv
![image](https://user-images.githubusercontent.com/15580867/78606573-29481600-7823-11ea-9fb2-e6285fbb67e8.png)

**Comment by mdibenigno** [comment]
This might be helpful - https://developers.google.com/public-data/docs/canonical/countries_csv  ...I was encountering the same mapping issues for France, US, New Zealand, and many others.

**Comment by hyperknot** [comment]
@tautme OK, we'll migrate to using iso1.json coordinates. I wanted to recommend it for performance reasons as well, but it seems they are not even calculated correctly.

**Comment by tautme** [comment]
@hyperknot I also checked iso2 for Alaska and the coordinates were correct. https://github.com/hyperknot/country-levels/blob/master/export/iso2.json

**Comment by tautme** [comment]
@hyperknot But in the FIPS.json the coordinates are incorrect for West Alaska. 
`fips:02016          16 02016 fips/02/02016.geojson Aleutians West Census Area Aleutians West Census Area, AK       5634              2          US-AK                AK America/Edmonton`
https://github.com/hyperknot/country-levels/blob/master/export/fips.json

**Comment by hyperknot** [comment]
You mean this GeoJSON? https://github.com/hyperknot/country-levels/blob/master/export/geojson/q8/fips/02/02016.geojson

**Comment by hyperknot** [comment]
OK, that's literally the only GeoJSON in the US which crosses the timeline and makes every GIS system crazy, isn't it? I think we can live with that. Is everything else OK?

**Comment by tautme** [comment]
OK, I checked the coordinates on the boundary of longitude ~0 and ~180 East and West. I can keep checking? But it looked good so far. Should I close this issue?

**Comment by hyperknot** [comment]
Sure, if you find any kind of error in country-levels then please open an issue there! Also, feel free to add a PR for the center fix json, it should be similar to the population fix json.

**Comment by hyperknot** [comment]
We'll close this once we migrate to using country-levels center.

**Comment by mdibenigno** [comment]
fyi... this is a wip 3d viz I'm building from this data, would love any feedback, and please excuse the bugs https://a.flow.gl/#/flow/k8qclvan

**Comment by fordmaxson** [comment]
Just checking if the fixes have made it to production in the timeseries.csv file?
As of 4/9/2020, I still see the US, France, and others off  location.

![image](https://user-images.githubusercontent.com/38134430/79044997-acc48700-7bd6-11ea-9a80-b23ec610849f.png)

**Comment by hyperknot** [comment]
Not yet, we are not yet using coordinates from country-levels. Soon it'll be fixed.

**Comment by jzohrab** [comment]
Fixed, closing.
